// Webamp's generic window (the frame Milkdrop's window uses), taken from webamp.js as
// it ships: its layout and the base skin's GEN.BMP sprites, scoped to .gen instead of
// #webamp so an app window can wear it. Writes gen-skin.css.
//   node tools/gen-skin.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const bundle = readFileSync(join(ROOT, 'webamp.js'), 'utf8');
// Rules as Webamp writes them, inside a JS string: "\n#webamp <selector> {<body>}".
const rule = /(?:\\n|\n)(#webamp [^{}]*?\.gen-[^{}]*?)\{([^{}]*)\}/g;
const css = ['/* Generated by tools/gen-skin.mjs from webamp.js (MIT): the generic window. */'];
const seen = new Set();
let m;
while ((m = rule.exec(bundle))) {
  const selector = m[1].replace(/\\n/g, ' ').replace(/#webamp/g, '.gen').replace(/\s+/g, ' ').trim();
  const body = m[2].replace(/\\n/g, '\n').replace(/\\'/g, "'").replace(/\\"/g, '"').trim();
  const text = `${selector} { ${body.replace(/\s*\n\s*/g, ' ')} }`;
  if (!seen.has(text)) seen.add(text), css.push(text);
}
writeFileSync(join(ROOT, 'gen-skin.css'), `${css.join('\n')}\n`);
console.log(`${css.length - 1} rules`);
