#!/usr/bin/env node
// A stopgap while the skin is redrawn in CSS (skin.css): the parts not redrawn yet
// keep Webamp's sprites, scaled 4× with xBR (ffmpeg) and shown at their size, in
// skin-images.css and skin/<n>.png. Parts already in CSS are skipped (DRAWN).
//   node tools/hd-skin.mjs
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SCALE = 4;
// What skin.css draws: the main window, and the equalizer (not its shade mode).
const DRAWN = /#main-window|#title-bar|\.actions|#eject|#shuffle|#repeat|#volume|#balance|#position|#clutter-bar|#button-|#play-pause|#work-indicator|\.digit-|#minus-sign|\.media-info|\.windows|#equalizer-button|#playlist-button|\.character|#about/;
const EQ_DRAWN = /#equalizer-window:not\(\.shade\)|\.equalizer-top|#on\b|#auto\b|#presets\b|#eqGraph|\.band|#preamp-line|#equalizer-window\.selected #eq-buttons|^#webamp #equalizer-shade/;
const bundle = readFileSync(join(ROOT, 'webamp.js'), 'utf8');
const out = join(ROOT, 'skin');
rmSync(out, { recursive: true, force: true });
mkdirSync(out);
const work = join(tmpdir(), `hd-skin-${process.pid}`);
mkdirSync(work, { recursive: true });

// Rules as Webamp writes them: "\n#webamp <selector>{background-image: url(data:…)}".
const rule = /\\n(#webamp [^{]{1,300})\{background-image: url\(data:image\/png;base64,([A-Za-z0-9+/=]+)\)/g;
const css = [
  '/* Generated by tools/hd-skin.mjs: sprites not yet redrawn in skin.css, 4× xBR. */',
  '#webamp, #webamp * { image-rendering: auto !important; }',
];
const byData = new Map();
let m;
let n = 0;
while ((m = rule.exec(bundle))) {
  const [, selector, data] = m;
  if (DRAWN.test(selector) && !/equalizer-window|playlist-window|gen-window/.test(selector)) continue;
  if (EQ_DRAWN.test(selector) && !/\.shade(?!\))/.test(selector)) continue;
  let name = byData.get(data);
  if (!name) {
    name = `${byData.size}.png`;
    byData.set(data, name);
    const png = Buffer.from(data, 'base64');
    const src = join(work, `in-${name}`);
    writeFileSync(src, png);
    execFileSync('ffmpeg', ['-loglevel', 'error', '-y', '-i', src, '-vf', `xbr=${SCALE}`, join(out, name)]);
  }
  const png = Buffer.from(data, 'base64');
  const width = png.readUInt32BE(16);
  const height = png.readUInt32BE(20);
  css.push(`${selector.replace(/\\"/g, '"')} { background-image: url("skin/${name}") !important; background-size: ${width}px ${height}px !important; }`);
  n++;
}
writeFileSync(join(ROOT, 'skin-images.css'), `${css.join('\n')}\n`);
rmSync(work, { recursive: true, force: true });
console.log(`${n} rules, ${byData.size} images`);
