#!/usr/bin/env node
// Makes Webamp's base skin sharp: takes every sprite Webamp embeds (its CSS rules with a
// data: PNG), scales it 4× with xBR (ffmpeg), which keeps the art's shapes and colors
// but rounds off the steps between pixels, and writes skin/<n>.png plus skin.css, which
// shows each at its original size. Run after updating webamp.js:
//   node tools/hd-skin.mjs
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SCALE = 4;
const bundle = readFileSync(join(ROOT, 'webamp.js'), 'utf8');
const out = join(ROOT, 'skin');
rmSync(out, { recursive: true, force: true });
mkdirSync(out);
const work = join(tmpdir(), `hd-skin-${process.pid}`);
mkdirSync(work, { recursive: true });

// Rules as Webamp writes them: "\n#webamp <selector>{background-image: url(data:…)}".
const rule = /\\n(#webamp [^{]{1,300})\{background-image: url\(data:image\/png;base64,([A-Za-z0-9+/=]+)\)/g;
const css = [
  '/* Generated by tools/hd-skin.mjs: Webamp base skin sprites, 4× xBR, shown at their size. */',
  '#webamp, #webamp * { image-rendering: auto !important; }',
];
const byData = new Map();
let m;
let n = 0;
while ((m = rule.exec(bundle))) {
  const [, selector, data] = m;
  let name = byData.get(data);
  if (!name) {
    name = `${byData.size}.png`;
    byData.set(data, name);
    const png = Buffer.from(data, 'base64');
    const src = join(work, `in-${name}`);
    writeFileSync(src, png);
    execFileSync('ffmpeg', ['-loglevel', 'error', '-y', '-i', src, '-vf', `xbr=${SCALE}`, join(out, name)]);
  }
  const png = Buffer.from(data, 'base64');
  const width = png.readUInt32BE(16);
  const height = png.readUInt32BE(20);
  css.push(`${selector.replace(/\\"/g, '"')} { background-image: url("skin/${name}") !important; background-size: ${width}px ${height}px !important; }`);
  n++;
}
writeFileSync(join(ROOT, 'skin.css'), `${css.join('\n')}\n`);
rmSync(work, { recursive: true, force: true });
console.log(`${n} rules, ${byData.size} images`);
